ethereum_rpc = "https://eth-hoodi.g.alchemy.com/v2/YOUR_KEY"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]
flash_activity_trap = { active = true, threshold = 5 }
